// <auto-generated />
using System;
using API_Painel_Investimentos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Painel_Investimentos.Data.Migrations
{
    [DbContext(typeof(DbPainelInvestimentoContext))]
    [Migration("20251121005807_CorrigindoAnottationsBancoNegocial")]
    partial class CorrigindoAnottationsBancoNegocial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ClienteEntity", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.InvestimentoEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rentabilidade")
                        .HasColumnType("REAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.PerfilRiscoEntity", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ProdutoEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("PerfilRiscoId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PrazoMinimoResgateMeses")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rentabilidade")
                        .HasColumnType("REAL");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRiscoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.SimulacaoEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorInvestido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.InvestimentoEntity", b =>
                {
                    b.HasOne("API_Painel_Investimentos.Data.Entities.ClienteEntity", "Cliente")
                        .WithMany("Investimentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ProdutoEntity", b =>
                {
                    b.HasOne("API_Painel_Investimentos.Data.Entities.PerfilRiscoEntity", "PerfilRisco")
                        .WithMany()
                        .HasForeignKey("PerfilRiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRisco");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.SimulacaoEntity", b =>
                {
                    b.HasOne("API_Painel_Investimentos.Data.Entities.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Painel_Investimentos.Data.Entities.ProdutoEntity", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Investimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
