// <auto-generated />
using System;
using API_Painel_Investimentos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Painel_Investimentos.Data.Migrations
{
    [DbContext(typeof(DbPainelInvestimentoContext))]
    partial class DbPainelInvestimentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ClienteEntity", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Pontuacao = (ushort)50
                        });
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.InvestimentoEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rentabilidade")
                        .HasColumnType("REAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Investimentos");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            ClienteId = 1u,
                            Data = new DateOnly(2025, 1, 1),
                            Rentabilidade = 0.085000000000000006,
                            Tipo = "CDB",
                            Valor = 10000.0
                        });
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.PerfilRiscoEntity", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco");

                    b.HasData(
                        new
                        {
                            Id = (ushort)1,
                            DescricaoPerfil = "Baixa exposição a risco, foco em preservação de capital.",
                            NomePerfil = "Conservador"
                        },
                        new
                        {
                            Id = (ushort)2,
                            DescricaoPerfil = "Equilíbrio entre risco e retorno.",
                            NomePerfil = "Moderado"
                        },
                        new
                        {
                            Id = (ushort)3,
                            DescricaoPerfil = "Alta exposição a risco, busca maior rentabilidade.",
                            NomePerfil = "Agressivo"
                        });
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ProdutoEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("PerfilRiscoId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PrazoMinimoResgateMeses")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rentabilidade")
                        .HasColumnType("REAL");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRiscoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Nome = "CDB Prefixado Caixa Liquidez diária",
                            PerfilRiscoId = (ushort)1,
                            PrazoMinimoResgateMeses = (ushort)0,
                            Rentabilidade = 0.085000000000000006,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 2u,
                            Nome = "Tesouro SELIC",
                            PerfilRiscoId = (ushort)1,
                            PrazoMinimoResgateMeses = (ushort)0,
                            Rentabilidade = 0.14999999999999999,
                            Risco = "Baixo",
                            Tipo = "TesouroDireto"
                        },
                        new
                        {
                            Id = 3u,
                            Nome = "CDB Prefixado Caixa Resgate 2 Anos",
                            PerfilRiscoId = (ushort)1,
                            PrazoMinimoResgateMeses = (ushort)24,
                            Rentabilidade = 0.10000000000000001,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 4u,
                            Nome = "LCI Caixa",
                            PerfilRiscoId = (ushort)2,
                            PrazoMinimoResgateMeses = (ushort)3,
                            Rentabilidade = 0.128,
                            Risco = "Medio",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 5u,
                            Nome = "Fundo de Investimento Caixa Multimercado",
                            PerfilRiscoId = (ushort)2,
                            PrazoMinimoResgateMeses = (ushort)6,
                            Rentabilidade = 0.12,
                            Risco = "Medio",
                            Tipo = "Fundo"
                        },
                        new
                        {
                            Id = 6u,
                            Nome = "FII Caixa Agências",
                            PerfilRiscoId = (ushort)3,
                            PrazoMinimoResgateMeses = (ushort)0,
                            Rentabilidade = 0.14999999999999999,
                            Risco = "Alto",
                            Tipo = "FII"
                        },
                        new
                        {
                            Id = 7u,
                            Nome = "Ações Caixa Seguridade",
                            PerfilRiscoId = (ushort)3,
                            PrazoMinimoResgateMeses = (ushort)0,
                            Rentabilidade = 0.17999999999999999,
                            Risco = "Alto",
                            Tipo = "Ações"
                        });
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.SimulacaoEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorInvestido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Simulacoes");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            ClienteId = 1u,
                            DataSimulacao = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PrazoMeses = (ushort)12,
                            ProdutoId = 1u,
                            ValorFinal = 10850.0,
                            ValorInvestido = 10000.0
                        });
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.InvestimentoEntity", b =>
                {
                    b.HasOne("API_Painel_Investimentos.Data.Entities.ClienteEntity", "Cliente")
                        .WithMany("Investimentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ProdutoEntity", b =>
                {
                    b.HasOne("API_Painel_Investimentos.Data.Entities.PerfilRiscoEntity", "PerfilRisco")
                        .WithMany()
                        .HasForeignKey("PerfilRiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilRisco");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.SimulacaoEntity", b =>
                {
                    b.HasOne("API_Painel_Investimentos.Data.Entities.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Painel_Investimentos.Data.Entities.ProdutoEntity", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Investimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
