// <auto-generated />
using System;
using API_Painel_Investimentos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Painel_Investimentos.Data.Migrations.DbTelemetria
{
    [DbContext(typeof(DbTelemetriaContext))]
    partial class DbTelemetriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("API_Painel_Investimentos.Data.Entities.TelemetriaEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CodEndpoint")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataRequisicao")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("TempoResposta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DadosTelemetria");
                });
#pragma warning restore 612, 618
        }
    }
}
